name: Egocentric test

on: 
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
    - name: Check out repository code
      uses: actions/checkout@v4
    - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - run: echo "💡 Python version ${{ matrix.python-version }} has been set up."
    - name: run Egocentric test code
      run: ../../python egocentric_check.py
  
      
      
    
